Profiles/urls.py
from django.urls import path
from . import views

app_name = 'Profiles'

urlpatterns = [
    path('',views.PostList.as_view(),name='postlist'),
    path('<int:pk>/',views.Detailview.as_view(),name='detail'),
    path('post/add/',views.addpost.as_view(),name='addpost'),
    path('post/<int:pk>/',views.updatepost.as_view(),name='updatepost'),
    path('post/drafts/',views.post_draftView.as_view() ,name='post_draft'),
    path('post/<int:pk>/publish/',views.publishpostView.as_view(),name='publishpost'),
    path('post/<int:pk>/delete/',views.PostDelete.as_view(),name='postdelete'),
    path('register/',views.UserformView.as_view(),name='register'),
    path('login/',views.LoginView.as_view(),{'template_name':'Profiles/login.html'}, name='login')
    ]

untitled2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Profiles/',include('Profiles.urls')),


]

Profiles/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post (models.Model):
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title =models.CharField(max_length=200)
    text = models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('Profiles:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

Profiles/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User

class Postform(forms.ModelForm):

    class Meta:
        model=Post
        fields=['text','title']

class Userform(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

Profiles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import generic
from .models import Post
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import View
from .forms import Postform , Userform
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login
from  django.contrib.auth.decorators import login_required


from django.utils import timezone

class PostList(generic.ListView):
    template_name ='Profiles/index.html'

    def get_queryset(self):
        return Post.objects.all()

class Detailview(generic.DetailView):
    model = Post
    template_name = 'Profiles/detail.html'


class addpost(CreateView):
    model = Post
    fields = ['title','text']
    form_class = Postform
    template_name = 'Profiles/post_form.html'


    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})


    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user

            post.save()
            return redirect('Profiles:detail', pk=post.pk)


"""def post_new(request):
    if request.method == "POST":
        form = Postform(request.POST)
        if form.is_valid():
          post = form.save(commit=False)
          post.author = request.user
          post.published_date = timezone.now()
          post.save()
          return redirect('Profiles:detail', pk=post.pk)
        else:
            form = Postform()
        return render(request, 'Profiles:updatepost', {'form': form})"""

class updatepost(UpdateView):
    model = Post
    fields = ['title','text']



class post_draftView(View):
    model = Post
    template_name = 'Profiles/post_drafts.html'

    def post_draft (self,request):
        posts=Post.objects.filter(published_date__isnull=True).order_by('created_date')
        return render(request,self.template_name,{'posts':posts})

class publishpostView(View):

    model =Post
    template_name = 'Profiles/detail.html'

    def postpublish (self,request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.publish()
        return redirect(self.template_name, pk=pk)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


class UserformView(View):
    form_class = Userform
    template_name = 'Profiles/registration_form.html'

    def get (self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            user.set_password(password)
            user.save()


            user=authenticate(username=username,password=password)
            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('Profiles:postlist')

        return render(request,self.template_name,{'form':form})


class PostDelete(DeleteView):
    model = Post
    success_url =reverse_lazy('Profiles:postlist')

class LoginView(View):
    template_name='Profiles/login.html'

Profiles/templates/Profiles/base.html
{% load staticfiles %}

<html>
<head>
    <title>My blogs</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">





    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"



    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'Profiles/style.css' %}">

    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

</head>
<body>
<div class="page-header">
    <a href="{% url 'Profiles:addpost' %}" class="top-menu">
                         <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;Add Post
                     </a>
    <h1><a href="{% url 'Profiles:postlist' %}">Your Own Blog</a></h1>
     <a href="{% url 'Profiles:login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>



</div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {%  block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

Profiles/templates/Profiles/detail.html
{%  extends 'Profiles/base.html' %}
{%  block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'Profiles:publishpost' pk=post.pk %}">Publish</a>
        {% endif %}
        <a class="btn btn-default" href="{% url 'Profiles:updatepost' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <form action="{% url 'Profiles:postdelete' pk=post.pk%}" method="post" style="display: inline-block;">
                     {% csrf_token %}
                     <input type="hidden" name="album_id" value="{{album.id}}"/>
                     <button type="submit" class="btn btn-default btn-sm">
                         <span class="glyphicon glyphicon-trash"></span>
                     </button>
                 </form>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

Profiles/templates/Profiles/form-template.html
{% for field in form %}
  <div class="form-group">
      <div class=" col-sm-offset-2  col-sm-10 ">
          <span class="text-danger small">{{field.errors}}</span>
      </div>
      <label class="control-label col-sm-2" >{{field.label_tag}}</label>
      <div class="col-sm-10">{{field}}</div>
  </div>
{% endfor %}

Profiles/templates/Profiles/index.html
{%  extends 'Profiles/base.html' %}

{% block content %}
{% for post in object_list %}
            <div class="post">
                <div class="date">
                    <p>published: {{ post.published_date }}</p>
                </div>
                    <h1><a href="{% url 'Profiles:detail' post.id %}">{{ post.title }}</a></h1>
                    <p>{{ post.text|linebreaksbr }}</p>

            </div>
{% endfor %}
{% endblock %}

Profiles/templates/Profiles/login.html
{% extends 'Profiles/base.html' %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a new account</h3>
                    <form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Profiles/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Profiles/templates/Profiles/post_draft.html
{%  extends 'Profiles/base.html'%}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'Profiles:detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

Profiles/templates/Profiles/post_form.html
{% extends 'Profiles/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Profiles/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="save btn btn-default">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Profiles/templates/Profiles/registration_form.html
{% extends 'Profiles/base.html' %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a new account</h3>
                    <form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Profiles/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}